source 'https://rubygems.org'

gem 'sinatra', '~> 1.4.6'
gem 'sinatra-contrib', '~> 1.4.4'
gem 'mysql2', '~> 0.3.18'
gem 'activerecord', '~> 4.2.2'
gem 'json', '~> 1.8.3'
gem 'omniauth', '~> 1.2.2'
gem 'omniauth-oauth2', '~> 1.1.2'
gem 'omniauth-slack'
